---
- name: Configure webserver using Docker
  hosts: ansible-controlnode-1

  tasks:
  - name: Adding Docker repository
    yum_repository:
      name: Docker
      description: Docker Repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no
      enabled: yes

  - name: Installing Docker package
    package:
      name:
        - "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: Installing python3 and python3-pip
    yum:
      name:
        - "python3"
        - "python3-pip"
      state: present

  - name: Installing Docker SDK for python3
    command: pip3 install docker

  - name: Installing Docker-compose SDK for python3
    command: pip3 install docker-compose

  - name: adding existing user to group docker
    command: usermod -aG docker $USER

  - name: Starting docker service
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: Creating a folder and copy html file...
    file:
      path: /ansible_code
      state: directory

  - name: Copying html files
    copy:
      src: "index.html"
      dest: "/ansible_code/"

  - name: Creating container using HTTPD Image
    docker_container:
      name: MyWebServer
      image: httpd
      state: started
      exposed_ports:
      - "80"
      ports:
      - "8888:80"
      volumes:
      - /webpages:/usr/local/apache2/htdocs/
